const posts = [
    {date: "10/30/1984",
    title: "My Musings On the Thing",
    post: <div><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis illum molestiae ipsa id maiores asperiores placeat officiis, odio facere totam aspernatur at aperiam voluptas exercitationem a consectetur enim dignissimos nobis distinctio. Fugiat, sequi. Animi accusamus, eos officiis labore fugit minima nulla doloribus quis, veritatis, porro aliquid magnam molestias nihil delectus. Ab dolor, asperiores delectus necessitatibus, maiores, aut magnam neque mollitia voluptatum sunt nobis provident ducimus voluptate exercitationem ullam saepe vel! Itaque alias repudiandae tempora maxime maiores culpa ratione nam, officiis, eveniet similique id voluptatem veritatis sed, eligendi suscipit. Eos qui quos itaque porro illum vitae sunt provident placeat facilis eveniet!</p> <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Est eligendi beatae aliquam dicta neque ipsa, voluptatibus rem ut, excepturi, voluptatem aut ea tempore distinctio saepe nihil at consequatur quasi! Eveniet praesentium, atque recusandae modi tempora quidem doloribus quos inventore aperiam perspiciatis asperiores impedit quam cupiditate explicabo dolorem fugiat, ipsa enim eius aliquid. Laboriosam, quos voluptatem praesentium possimus provident earum officia reiciendis aperiam eveniet dolores iste, totam est. Doloremque nihil facilis natus cumque mollitia! Dolor nisi ut excepturi, animi obcaecati ad consequatur tempora explicabo culpa, libero, sunt minima dolorem accusamus incidunt suscipit iure? Voluptates ratione quibusdam ad sit. Quae, explicabo vel.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, a? Deserunt, voluptas inventore modi sequi suscipit harum ex non maiores earum, assumenda laboriosam. Modi ea quas sapiente optio delectus laborum iste quo id inventore, voluptate dignissimos ut necessitatibus sed, eveniet, illo accusamus. Nemo dolorum ad, accusamus amet corrupti itaque odit dicta obcaecati optio est deserunt atque pariatur at! Velit, repellat! Est, voluptatibus veniam accusamus asperiores veritatis fugit reiciendis vel optio praesentium numquam esse laboriosam maxime soluta dicta nemo, sunt atque natus odio. Voluptatum eos mollitia eaque facilis eligendi aut temporibus veniam laboriosam ut aperiam quos, optio qui esse ducimus delectus.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet dolorum dolores libero iusto doloremque repellat pariatur in animi nesciunt natus, facere quod delectus labore! Ipsum quidem commodi reprehenderit dolorum animi.</p>
    </div>
    },
    {date: "5/30/2023",
    title: "My Feelings About Feelings",
    post: <div><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis illum molestiae ipsa id maiores asperiores placeat officiis, odio facere totam aspernatur at aperiam voluptas exercitationem a consectetur enim dignissimos nobis distinctio. Fugiat, sequi. Animi accusamus, eos officiis labore fugit minima nulla doloribus quis, veritatis, porro aliquid magnam molestias nihil delectus. Ab dolor, asperiores delectus necessitatibus, maiores, aut magnam neque mollitia voluptatum sunt nobis provident ducimus voluptate exercitationem ullam saepe vel! Itaque alias repudiandae tempora maxime maiores culpa ratione nam, officiis, eveniet similique id voluptatem veritatis sed, eligendi suscipit. Eos qui quos itaque porro illum vitae sunt provident placeat facilis eveniet!</p> <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Est eligendi beatae aliquam dicta neque ipsa, voluptatibus rem ut, excepturi, voluptatem aut ea tempore distinctio saepe nihil at consequatur quasi! Eveniet praesentium, atque recusandae modi tempora quidem doloribus quos inventore aperiam perspiciatis asperiores impedit quam cupiditate explicabo dolorem fugiat, ipsa enim eius aliquid. Laboriosam, quos voluptatem praesentium possimus provident earum officia reiciendis aperiam eveniet dolores iste, totam est. Doloremque nihil facilis natus cumque mollitia! Dolor nisi ut excepturi, animi obcaecati ad consequatur tempora explicabo culpa, libero, sunt minima dolorem accusamus incidunt suscipit iure? Voluptates ratione quibusdam ad sit. Quae, explicabo vel.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, a? Deserunt, voluptas inventore modi sequi suscipit harum ex non maiores earum, assumenda laboriosam. Modi ea quas sapiente optio delectus laborum iste quo id inventore, voluptate dignissimos ut necessitatibus sed, eveniet, illo accusamus. Nemo dolorum ad, accusamus amet corrupti itaque odit dicta obcaecati optio est deserunt atque pariatur at! Velit, repellat! Est, voluptatibus veniam accusamus asperiores veritatis fugit reiciendis vel optio praesentium numquam esse laboriosam maxime soluta dicta nemo, sunt atque natus odio. Voluptatum eos mollitia eaque facilis eligendi aut temporibus veniam laboriosam ut aperiam quos, optio qui esse ducimus delectus.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet dolorum dolores libero iusto doloremque repellat pariatur in animi nesciunt natus, facere quod delectus labore! Ipsum quidem commodi reprehenderit dolorum animi.</p>
    </div>
    },
    {date: "6/15/2023",
    title: "My Addiction to Addictions",
    post: <div><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis illum molestiae ipsa id maiores asperiores placeat officiis, odio facere totam aspernatur at aperiam voluptas exercitationem a consectetur enim dignissimos nobis distinctio. Fugiat, sequi. Animi accusamus, eos officiis labore fugit minima nulla doloribus quis, veritatis, porro aliquid magnam molestias nihil delectus. Ab dolor, asperiores delectus necessitatibus, maiores, aut magnam neque mollitia voluptatum sunt nobis provident ducimus voluptate exercitationem ullam saepe vel! Itaque alias repudiandae tempora maxime maiores culpa ratione nam, officiis, eveniet similique id voluptatem veritatis sed, eligendi suscipit. Eos qui quos itaque porro illum vitae sunt provident placeat facilis eveniet!</p> <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Est eligendi beatae aliquam dicta neque ipsa, voluptatibus rem ut, excepturi, voluptatem aut ea tempore distinctio saepe nihil at consequatur quasi! Eveniet praesentium, atque recusandae modi tempora quidem doloribus quos inventore aperiam perspiciatis asperiores impedit quam cupiditate explicabo dolorem fugiat, ipsa enim eius aliquid. Laboriosam, quos voluptatem praesentium possimus provident earum officia reiciendis aperiam eveniet dolores iste, totam est. Doloremque nihil facilis natus cumque mollitia! Dolor nisi ut excepturi, animi obcaecati ad consequatur tempora explicabo culpa, libero, sunt minima dolorem accusamus incidunt suscipit iure? Voluptates ratione quibusdam ad sit. Quae, explicabo vel.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, a? Deserunt, voluptas inventore modi sequi suscipit harum ex non maiores earum, assumenda laboriosam. Modi ea quas sapiente optio delectus laborum iste quo id inventore, voluptate dignissimos ut necessitatibus sed, eveniet, illo accusamus. Nemo dolorum ad, accusamus amet corrupti itaque odit dicta obcaecati optio est deserunt atque pariatur at! Velit, repellat! Est, voluptatibus veniam accusamus asperiores veritatis fugit reiciendis vel optio praesentium numquam esse laboriosam maxime soluta dicta nemo, sunt atque natus odio. Voluptatum eos mollitia eaque facilis eligendi aut temporibus veniam laboriosam ut aperiam quos, optio qui esse ducimus delectus.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet dolorum dolores libero iusto doloremque repellat pariatur in animi nesciunt natus, facere quod delectus labore! Ipsum quidem commodi reprehenderit dolorum animi.</p>
    </div>
    },
    {date: "7/20/2023",
    title: "My Obsession with This Obscure Thing",
    post: <div><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis illum molestiae ipsa id maiores asperiores placeat officiis, odio facere totam aspernatur at aperiam voluptas exercitationem a consectetur enim dignissimos nobis distinctio. Fugiat, sequi. Animi accusamus, eos officiis labore fugit minima nulla doloribus quis, veritatis, porro aliquid magnam molestias nihil delectus. Ab dolor, asperiores delectus necessitatibus, maiores, aut magnam neque mollitia voluptatum sunt nobis provident ducimus voluptate exercitationem ullam saepe vel! Itaque alias repudiandae tempora maxime maiores culpa ratione nam, officiis, eveniet similique id voluptatem veritatis sed, eligendi suscipit. Eos qui quos itaque porro illum vitae sunt provident placeat facilis eveniet!</p> <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Est eligendi beatae aliquam dicta neque ipsa, voluptatibus rem ut, excepturi, voluptatem aut ea tempore distinctio saepe nihil at consequatur quasi! Eveniet praesentium, atque recusandae modi tempora quidem doloribus quos inventore aperiam perspiciatis asperiores impedit quam cupiditate explicabo dolorem fugiat, ipsa enim eius aliquid. Laboriosam, quos voluptatem praesentium possimus provident earum officia reiciendis aperiam eveniet dolores iste, totam est. Doloremque nihil facilis natus cumque mollitia! Dolor nisi ut excepturi, animi obcaecati ad consequatur tempora explicabo culpa, libero, sunt minima dolorem accusamus incidunt suscipit iure? Voluptates ratione quibusdam ad sit. Quae, explicabo vel.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, a? Deserunt, voluptas inventore modi sequi suscipit harum ex non maiores earum, assumenda laboriosam. Modi ea quas sapiente optio delectus laborum iste quo id inventore, voluptate dignissimos ut necessitatibus sed, eveniet, illo accusamus. Nemo dolorum ad, accusamus amet corrupti itaque odit dicta obcaecati optio est deserunt atque pariatur at! Velit, repellat! Est, voluptatibus veniam accusamus asperiores veritatis fugit reiciendis vel optio praesentium numquam esse laboriosam maxime soluta dicta nemo, sunt atque natus odio. Voluptatum eos mollitia eaque facilis eligendi aut temporibus veniam laboriosam ut aperiam quos, optio qui esse ducimus delectus.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet dolorum dolores libero iusto doloremque repellat pariatur in animi nesciunt natus, facere quod delectus labore! Ipsum quidem commodi reprehenderit dolorum animi.</p>
    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Corporis, enim. Incidunt totam reprehenderit quod, earum laborum non dolores. Eos dolore perferendis porro assumenda quis impedit quasi? In tempore consequatur velit eligendi atque odio fuga nulla ab ea vitae, nihil ratione explicabo voluptatem reprehenderit itaque, quaerat aspernatur neque rem magni sapiente doloribus voluptate perferendis! Eligendi, voluptatibus libero! Architecto ad ducimus, illum blanditiis reiciendis omnis fugit. Deleniti tenetur nesciunt temporibus? Vitae veniam ipsa necessitatibus.</p>
    </div>
    },
    {date: "8/24/2023",
    title: "My Preoccupation With Hotdogs",
    post: <div><p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Blanditiis illum molestiae ipsa id maiores asperiores placeat officiis, odio facere totam aspernatur at aperiam voluptas exercitationem a consectetur enim dignissimos nobis distinctio. Fugiat, sequi. Animi accusamus, eos officiis labore fugit minima nulla doloribus quis, veritatis, porro aliquid magnam molestias nihil delectus. Ab dolor, asperiores delectus necessitatibus, maiores, aut magnam neque mollitia voluptatum sunt nobis provident ducimus voluptate exercitationem ullam saepe vel! Itaque alias repudiandae tempora maxime maiores culpa ratione nam, officiis, eveniet similique id voluptatem veritatis sed, eligendi suscipit. Eos qui quos itaque porro illum vitae sunt provident placeat facilis eveniet!</p> <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Est eligendi beatae aliquam dicta neque ipsa, voluptatibus rem ut, excepturi, voluptatem aut ea tempore distinctio saepe nihil at consequatur quasi! Eveniet praesentium, atque recusandae modi tempora quidem doloribus quos inventore aperiam perspiciatis asperiores impedit quam cupiditate explicabo dolorem fugiat, ipsa enim eius aliquid. Laboriosam, quos voluptatem praesentium possimus provident earum officia reiciendis aperiam eveniet dolores iste, totam est. Doloremque nihil facilis natus cumque mollitia! Dolor nisi ut excepturi, animi obcaecati ad consequatur tempora explicabo culpa, libero, sunt minima dolorem accusamus incidunt suscipit iure? Voluptates ratione quibusdam ad sit. Quae, explicabo vel.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Qui, a? Deserunt, voluptas inventore modi sequi suscipit harum ex non maiores earum, assumenda laboriosam. Modi ea quas sapiente optio delectus laborum iste quo id inventore, voluptate dignissimos ut necessitatibus sed, eveniet, illo accusamus. Nemo dolorum ad, accusamus amet corrupti itaque odit dicta obcaecati optio est deserunt atque pariatur at! Velit, repellat! Est, voluptatibus veniam accusamus asperiores veritatis fugit reiciendis vel optio praesentium numquam esse laboriosam maxime soluta dicta nemo, sunt atque natus odio. Voluptatum eos mollitia eaque facilis eligendi aut temporibus veniam laboriosam ut aperiam quos, optio qui esse ducimus delectus.</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eveniet dolorum dolores libero iusto doloremque repellat pariatur in animi nesciunt natus, facere quod delectus labore! Ipsum quidem commodi reprehenderit dolorum animi.</p>
    </div>
    },
]

export default posts